name: flutter_wisata_candi
description: "Flutter Project to Display Wisata Candi"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  shared_preferences:
  flutter_launcher_icons:
  cached_network_image:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "images/logo_wisata_candi.png"

flutter:
  uses-material-design: true
  assets:
    - images/
